/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    LoadingCard: typeof import('./src/components/LoadingCard.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    News: typeof import('./src/components/Tabs/News.vue')['default']
    Socials: typeof import('./src/components/Socials.vue')['default']
    Team: typeof import('./src/components/Tabs/Team.vue')['default']
    Updates: typeof import('./src/components/Tabs/Updates.vue')['default']
  }
}
